#! /usr/bin/bash

# This is free and unencumbered software released into the public domain.
# 
# Anyone is free to copy, modify, publish, use, compile, sell, or distribute this software,
# either in source code form or as a compiled binary, for any purpose, commercial or non-commercial,
# and by any means.
# 
# In jurisdictions that recognize copyright laws, the author or authors of this software dedicate
# any and all copyright interest in the software to the public domain. We make this dedication for
# the benefit of the public at large and to the detriment of our heirs and successors. We intend
# this dedication to be an overt act of relinquishment in perpetuity of all present and future rights
# to this software under copyright law.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
# NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
# 
# For more information, please refer to <https://unlicense.org/>

SNAP_DIR="/.snapshots"
ROOT_PREFIX="@"
HOME_PREFIX="@home"
SCRIPT_PATH=$(command -v "$0")

list () {
    # freq: (frequency of the cron job, e.g., hourly, daily, weekly, monthly, yearly)
    freq="$1"

    if [ -n "$freq" ]; then
        # List all matching snapshots, sorted
        mapfile -t roots < <(find "$SNAP_DIR" -maxdepth 1 -name "${ROOT_PREFIX}-*-$freq" | sort)

        for root in "${roots[@]}"; do
            home=$(sed -n "s|${ROOT_PREFIX}|${HOME_PREFIX}|p" <<< "$root")

            echo "$root"

            if [ -n "$home" ]; then
                echo "$home"
            fi
        done
        exit 0
    fi

    # If no frequency is given, repeat for each frequency
    for freq in hourly daily weekly monthly yearly; do
        echo "--- $freq ---"
        "$FUNCNAME" "$freq"
    done
}

schedule () {
    # $freq: (e.g., frequency)
    freq="$1"
    # $maxn: confirming if you want snap home (empty will not snapshot)
    maxn="$2"
    # $with_home: if you want to snapshot home (with-home or empty)
    with_home="$3"

    if [ -z "$freq" ]; then
        echo "frequency not defined"
        exit 1
    fi

    if [ -z "$maxn" ]; then
        echo "max number of snapshots not defined"
        exit 1
    fi

    case "$freq" in
        hourly)  cron_freq="0 * * * *" ;;      # every hour at minute 0
        daily)   cron_freq="0 12 * * *" ;;     # every day at 12:00 (noon)
        weekly)  cron_freq="0 12 * * 0" ;;     # every Sunday at 12:00 (noon)
        monthly) cron_freq="0 12 1 * *" ;;     # first day of month at 12:00 (noon)
        yearly)  cron_freq="0 12 1 1 *" ;;     # January 1st at 12:00 (noon)
        *) echo "frequency not supported, use hourly, daily, weekly, monthly or yearly"; exit 1 ;;
    esac

    verify_cron=$(crontab -l 2>/dev/null | grep ".* $SCRIPT_PATH execute $freq.*" || echo "")

    if [ -z "$verify_cron" ]; then
        echo "adding cron job for $SCRIPT_PATH execute $freq $maxn $with_home"
        (crontab -l 2>/dev/null; echo "$cron_freq $SCRIPT_PATH execute $freq $maxn $with_home") | crontab -
    else
        echo "overriding cron job for $SCRIPT_PATH execute $maxn $freq"
        (sed 's\.* '"$SCRIPT_PATH"' execute .*\"'"$cron_freq"' '"$SCRIPT_PATH"' execute '"$freq"' '"$maxn"' '"$with_home"'\' <(crontab -l)) | crontab -
    fi
}

execute () {
    # $suffix: (e.g., frequency or apt)
    suffix="$1"
    # $maxn: 
    maxn="$2"
    # $maxn: confirming if you want snap home (empty will not snapshot)
    snap_home="$3"

    root_verify=$(mount | grep " / " | grep "btrfs")

    if [ -z "$root_verify" ]; then
        echo "root is not a subvolume"
        exit 1
    fi

    snapshots_verify=$(mount | grep " $SNAP_DIR " | grep "btrfs")

    if [ -z "$snapshots_verify" ]; then
        echo "$SNAP_DIR not found, maybe is not a subvolume?"
    fi

    if [ -z "$suffix" ]; then
        help
        exit 1
    fi

    if [ -z "$maxn" ]; then
        echo "max number of snapshots not defined"
        exit 1
    fi

    if [ "$snap_home" = "with-home" ]; then
        home_verify=$(mount | grep " /home " | grep "btrfs")

        if [ -n "$home_verify" ]; then
            answer="y"
        fi
    fi

    DATE=$(date +%Y-%m-%d_%H-%M-%S)

    btrfs subvolume snapshot "/" "${SNAP_DIR}/${ROOT_PREFIX}-${DATE}-${suffix}"

    if [ "$answer" = "y" ] || [ "$answer" = "Y" ]; then
        btrfs subvolume snapshot "/home" "${SNAP_DIR}/${HOME_PREFIX}-${DATE}-${suffix}"
    fi

    sh -c 'exec grub-mkconfig -o /boot/grub/grub.cfg "$@"'

    rm_old_snapshots "$suffix" "$maxn" "$snap_home"
}

rm_snapshot () {
    subvol="$1"

    if [ -z "$subvol" ]; then
        echo "subvolume not defined"
        exit 1
    fi

    btrfs subvolume delete "$subvol"
}

rm_old_snapshots () {
    # $suffix: (e.g., frequency or apt)
    suffix="$1"
    # $maxn: confirming if you want snap home (empty will not snapshot)
    maxn="$2"

    if [ -z "$suffix" ]; then
        echo "suffix not defined"
        exit 1
    fi

    if [ -z "$maxn" ]; then
        echo "max number of snapshots not defined"
        exit 1
    fi

    # Find matching snapshots
    mapfile -t snaps < <(find "$SNAP_DIR" -maxdepth 1 -name "${ROOT_PREFIX}-*-$suffix" | sort)
    snap_count="${#snaps[@]}"

    if [ "$snap_count" -le "$maxn" ]; then
        echo "no old snapshots found"
        return 0
    fi

    echo "deleting old snapshots, keeping only the last $maxn"
    to_delete_count=$(($snap_count - $maxn))
    for ((i=0; i<to_delete_count; i++)); do
        home_snap="${snaps[$i]}"'/'"${ROOT_PREFIX}"'/'"${HOME_PREFIX}"

        if [ -d "$home_snap" ]; then
            rm_snapshot "$home_snap"
        fi

        rm_snapshot "${snaps[$i]}"
    done
}

apt_config () {
    maxn="$1"

    if [ -z "$maxn" ]; then
        echo "max number of snapshots not defined"
        exit 1
    fi

    if [ -z "$(apt --version 2>/dev/null)" ]; then
        echo "apt not found, maybe you are not using debian or ubuntu?"
        exit 1
    fi

    sh -c "echo 'DPkg::Pre-Invoke { \"$SCRIPT_PATH execute apt $maxn\"; };' > /etc/apt/apt.conf.d/99customautosnap"
    cat /etc/apt/apt.conf.d/99customautosnap
}

search_for_installer () {
    if [ -n "$(apt --version 2>/dev/null)" ]; then
        installer="apt"
        installarg="install"
    elif [ -n "$(dnf --version 2>/dev/null)" ]; then
        installer=dnf
        installarg="install"
    elif [ -n "$(pacman --version 2>/dev/null)" ]; then
        installer="pacman"
        installarg="-S"
    else
        echo "installer not supported"
        exit 1
    fi

    echo "$installer" "$installarg"
}

grub_btrfs () {
    installercmd="$1 $2"

    if [ "$installercmd" = " " ]; then
        installercmd="$(search_for_installer)"
    elif [ -z "$2" ]; then
        echo "defined installer '$1', but no install arg defined."
        exit 1
    fi

    if [ -z "$installercmd" ]; then
        echo "installer not supported"
        exit 1
    fi


    while [ "$answer" != "Y" ] && [ "$answer" != "y" ] && [ "$answer" != "N" ] && [ "$answer" != "n" ]; do
        echo "it will install make btrfs-progs gawk git, you want to continue? (Y/n)"
        read answer
    done

    if [ "$answer" = "N" ] | [ "$answer" = "n" ]; then
        echo "install aborted."
        exit 1
    fi

    sh -c "$installercmd make btrfs-progs gawk git -y"
    git clone "https://github.com/antynea/grub-btrfs" /tmp/grub-btrfs
    cd /tmp/grub-btrfs
    make install
    cd ../
    rm -rf /tmp/grub-btrfs
}

help () {
    echo "list [<suffix>]			list snapshots, if suffix is defined, it will list only the snapshots with that suffix"
    echo "execute <suffix> <maxn> <with-home>	snapshot root and maybe home (used for mark the frequency or the installer)"
    echo "rmold <suffix> <maxn> <with-home>	remove old snapshots, keeping only the last maxn (used for mark the frequency or the installer)"
    echo "config-apt <maxn>			configure apt to snapshot before install, keeping only the last maxn"
    echo "sched <frequency> <maxn> <with-home>	schedule a snapshot with frequency, keeping only the last maxn (with-home or empty)"
    echo "grub-btrfs <installer> <installarg>	install and configure grub-btrfs, if no installer is defined, it will search for apt, dnf or pacman"
    echo "help					show this message"
}

set -e
option="$1"
shift

user_not_root_error_msg () {
    echo "You must run this script as root or with sudo."
    exit 1
}

if [ "$(id -u)" != "0" ]; then
    case $option in
        list) ;;
        execute) user_not_root_error_msg ;;
        rmold) user_not_root_error_msg ;;
        config-apt) user_not_root_error_msg ;;
        sched) user_not_root_error_msg ;;
        grub-btrfs) user_not_root_error_msg ;;
        help) ;;
        *) help; exit 1 ;;
    esac
fi

case $option in
    list) list "$1" ;;
    execute) execute "$1" "$2" "$3" ;;
    rmold) rm_old_snapshots "$1" "$2" "$3" ;;
    config-apt) apt_config "$1" ;;
    sched) schedule "$1" "$2" "$3" ;;
    grub-btrfs) grub_btrfs "$1" "$2" ;;
    help) help ;;
    *) help; exit 1 ;;
esac
